name = "up-anonymous-protest-portal"
main = "./src/worker.ts"
compatibility_date = "2026-05-22"
workers_dev = true

[assets]
directory = "./dist"

[vars]
TURNSTILE_SITE_KEY = "0x4AAAAAADU8-xhjM-jNwn_H"
TURNSTILE_EXPECTED_ACTION = "vote"
TURNSTILE_EXPECTED_HOSTNAME = "nouniformcampusup.me"
TALLY_CACHE_TTL = "10"
LEADERBOARD_CACHE_TTL = "20"

[[d1_databases]]
binding = "VOTES_DB"
database_name = "votes_db"
database_id = "b125c9f1-027f-4f07-804e-7d19c13e297e"

[[d1_databases]]
binding = "COLLEGES_DB"
database_name = "colleges_db"
database_id = "eb17d597-2096-4ef3-b3f3-4e6049674cd8"

[[queues.producers]]
binding = "VOTE_EVENTS"
queue = "vote-events"

[[queues.consumers]]
queue = "vote-events"
max_batch_size = 100
max_batch_timeout = 5

[[kv_namespaces]]
binding = "SESSION"
id = "2611871aa4a24f88b6fb2a68f7b14ecb"

[triggers]
crons = ["*/10 * * * *"]

[env.staging]
[env.staging.vars]
TURNSTILE_SITE_KEY = "0x4AAAAAADU8-xhjM-jNwn_H"
TURNSTILE_EXPECTED_ACTION = "vote"
TURNSTILE_EXPECTED_HOSTNAME = "nouniformcampusup.me"
TALLY_CACHE_TTL = "10"
LEADERBOARD_CACHE_TTL = "20"

[[env.staging.d1_databases]]
binding = "VOTES_DB"
database_name = "votes_db_staging"
database_id = "980f5e94-3221-4810-aec1-62203a089bc0"

[[env.staging.d1_databases]]
binding = "COLLEGES_DB"
database_name = "colleges_db_staging"
database_id = "5e8b0298-37a1-40c4-a525-b9d177966f5e"

[[env.staging.queues.producers]]
binding = "VOTE_EVENTS"
queue = "vote-events-staging"

[[env.staging.queues.consumers]]
queue = "vote-events-staging"
max_batch_size = 100
max_batch_timeout = 5

[[env.staging.kv_namespaces]]
binding = "SESSION"
id = "2611871aa4a24f88b6fb2a68f7b14ecb"

[env.staging.triggers]
crons = ["*/10 * * * *"]

[env.production]
[env.production.vars]
TURNSTILE_SITE_KEY = "0x4AAAAAADU8-xhjM-jNwn_H"
TURNSTILE_EXPECTED_ACTION = "vote"
TURNSTILE_EXPECTED_HOSTNAME = "nouniformcampusup.me"
TALLY_CACHE_TTL = "10"
LEADERBOARD_CACHE_TTL = "20"

[[env.production.d1_databases]]
binding = "VOTES_DB"
database_name = "votes_db_prod"
database_id = "77a55f35-1c9b-4092-a545-4a72c4af68b6"

[[env.production.d1_databases]]
binding = "COLLEGES_DB"
database_name = "colleges_db_prod"
database_id = "e38180e2-acae-4071-bb30-af95f70c9f5c"

[[env.production.queues.producers]]
binding = "VOTE_EVENTS"
queue = "vote-events-prod"

[[env.production.queues.consumers]]
queue = "vote-events-prod"
max_batch_size = 100
max_batch_timeout = 5

[[env.production.kv_namespaces]]
binding = "SESSION"
id = "2611871aa4a24f88b6fb2a68f7b14ecb"

[env.production.triggers]
crons = ["*/5 * * * *"]