INSERT OR IGNORE INTO colleges_list (id, college_name, district) VALUES
  (1, 'University of Lucknow', 'Lucknow'),
  (2, 'Banaras Hindu University', 'Varanasi'),
  (3, 'Aligarh Muslim University', 'Aligarh'),
  (4, 'Allahabad University', 'Prayagraj'),
  (5, 'Dr. Ram Manohar Lohia Avadh University', 'Ayodhya'),
  (6, 'Chhatrapati Shahu Ji Maharaj University', 'Kanpur Nagar'),
  (7, 'Mahatma Jyotiba Phule Rohilkhand University', 'Bareilly'),
  (8, 'Sampurnanand Sanskrit University', 'Varanasi'),
  (9, 'Madan Mohan Malaviya University of Technology', 'Gorakhpur'),
  (10, 'Harcourt Butler Technical University', 'Kanpur Nagar'),
  (11, 'Dr. A.P.J. Abdul Kalam Technical University', 'Lucknow'),
  (12, 'King George''s Medical University', 'Lucknow'),
  (13, 'Gautam Buddha University', 'Gautam Buddha Nagar'),
  (14, 'Bundelkhand University', 'Jhansi'),
  (15, 'M.J.P. Rohilkhand University Campus College', 'Bareilly'),
  (16, 'Deen Dayal Upadhyaya Gorakhpur University', 'Gorakhpur'),
  (17, 'Mahatma Gandhi Kashi Vidyapith', 'Varanasi'),
  (18, 'Uttar Pradesh Rajarshi Tandon Open University', 'Prayagraj'),
  (19, 'Chaudhary Charan Singh University', 'Meerut'),
  (20, 'Narendra Dev University of Agriculture and Technology', 'Ayodhya'),
  (21, 'Sardar Vallabhbhai Patel University of Agriculture and Technology', 'Meerut'),
  (22, 'CSN PG College', 'Hardoi'),
  (23, 'National PG College', 'Lucknow'),
  (24, 'Isabella Thoburn College', 'Lucknow'),
  (25, 'Christ Church College', 'Kanpur Nagar');
